# Generated by Django 4.2.6 on 2025-05-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_option_question_useranswer_option_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswer",
            old_name="quesdtion",
            new_name="question",
        ),
    ]
